version: 0.2

env:
  variables:
    REGION: eu-north-1
    REPOSITORY_NAME: fastapi-server

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - docker build -t $REPOSITORY_NAME .
      - docker tag $REPOSITORY_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:latest
    
  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - aws ecs update-service --cluster fastapi-cluster --service fastapi-service --force-new-deployment --region eu-north-1